Repository adessoAG/jekyll2cms, pull requests merged in 2020-04, with the labels that each got.

#83 change strategy to generate everything not in future and filter by git
  .github/workflows/docker-build-and-push.yml
  src/main/java/de/adesso/service/FileTransfer.java
  src/main/java/de/adesso/service/GitRepoDiffer.java
  src/main/java/de/adesso/service/GitRepoPusher.java
  src/main/java/de/adesso/service/InitializationService.java
  src/main/java/de/adesso/service/MarkdownTransformer.java
Labels: feature

#84 Remove version
  Dockerfile
  build.gradle
Labels: optimization

#85 Refactoring Sergej
  src/main/java/de/adesso/service/ConfigService.java
Labels: documentation, nice-to-have, task

#78 Updated Release 2.1.0
  .github/workflows/docker-build-and-push.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  src/main/java/de/adesso/service/ConfigService.java
  src/main/java/de/adesso/service/FileTransfer.java
  src/main/java/de/adesso/service/GitRepoCloner.java
  src/main/java/de/adesso/service/GitRepoDiffer.java
  src/main/java/de/adesso/service/GitRepoPusher.java
  src/main/java/de/adesso/service/InitializationService.java
  src/main/java/de/adesso/service/JekyllService.java
  src/main/java/de/adesso/service/MarkdownTransformer.java
  src/main/java/de/adesso/service/StreamGobbler.java
  src/main/resources/application.properties
Labels: feature, optimization

#91 remove unused files
  .travis.yml
  bin/application-sample.properties
  bin/banner.txt
  bin/logback-spring.xml
  bin/mdFiles/front_matter_test.md
  bin/mdFiles/front_matter_test.yml
  images/resized-images/logo-2x_small_320.png
  images/resized-images/octojekyll_medium_570.png
  images/resized-images/octojekyll_small_320.png
  rebuildAndRun-unix-host.sh
  rebuildAndRun-windows-host.bat
  src/test/resources/mdFiles/front_matter_test.md
  src/test/resources/mdFiles/front_matter_test.yml
  todo.md
Labels: optimization

#93 Release: Fix file creation
  src/main/java/de/adesso/service/MarkdownTransformer.java
Labels: bug, optimization
